racer-rust/emacs-racer

Cask

Cask reads those information from Package-Requires header of racer.el
by package-file.

Remove duplications

---

racer.el

Completions should now be triggered after typing `.` or `::`.
(Works once company-mode is updated on MELPA)

Add property function for :company-prefix-length

---

README.md

Add a mention of how to jump back after reading the definition of a symbol.

Mention the shortcut key for 'pop-tag-mark.

---

racer.el

The default value for `completion-at-point-functions` is
`'(tags-completion-at-point-function)`. As a result, if the user has any
tags tables in `tagsl-table-list` then `company-capf` tries to use those
tags tables for completions.
Instead, we ensure that `completion-at-point-functions` is initialised
to nil, so rust-mode buffers don't end up using these unwanted other
completion sources.
@fbergroth does this look reasonable to you? I'm still learning about CAPF.

Only use racer for completions in rust-mode.

---

racer.el

* set default-directory for racer-comand to a parent directory
containing a Cargo.toml
* add a option to set CARGO_HOME to support rustup installations

Fix completion of third party crates

---

racer.el

This PR fixes the completion text for StructField completion candidates:
Before:
After:

Fixed formatting of StructField completions

---

racer.el
test/racer-test.el

This command fetches the docstring of the function or type at point. It
then renders the markdown in a separate buffer, so users can learn about
functionality with reading the implementation.
Anyone willing to do a quick review? Sorry it's a big patch. cc @ane @fbergroth

Add a racer-describe command.

---

racer.el

A misconfiguration of racer.el can cause a `user-error` in
`racer--call`. In this situation, `(delete-file tmp-file)` is never
executed causing a leak of a temp-file.

Use `unwind-protect` to make sure tmp-files get deleted

---

racer.el

Some ways of changing the displayed contents of the buffer do not play well with the current way of calculating the column offset.
For example, I wanted to use Fira Code with racer-mode. I found this trick to make firacode work:
https://gist.github.com/mordocai/50783defab3c3d1650e068b4d1c91495
The problem is that using font-lock-symbols to change the displayed symbol (replacing 2 glyphs with 1 glyph) is throwing off the column calculation in racer mode. The code in this pull request uses the string-width of the underlying string representation to calculate the column. This should match what racer sees when it parses the file.
I don't know if I applied this fix to all the places where columns are used. I could use some code review for that. Doing the calculation this way should also future …

Fix column calculations when symbol rewriting is in effect

---

racer.el

This commit changes the behavior of `racer--call` to dynamically expand
`RUST_SRC_PATH` and `CARGO_HOME`. This is useful if these environment variables
aren't set at the time emacs is started.
I'm working on a tool to dynamically apply development environments from
direnv[1] when opening files in Emacs. This is useful to set
`RUST_SRC_PATH` to different values for each project (without resorting
to directory-local variables). This commit is necessary to support this
in racer.
The current behavior is preserved. Priority is given to the `defcustom` variables and the environment variables are used as a fallback. I also removed the `getenv` calls from the default values of the `defcustom` variables as this isn't necessary anymore. 
[1]: https://github.com/direnv/direnv

Dynamically expand RUST_SRC_PATH and CARGO_HOME.

---

racer.el

Fixes issue #54. Works for both old and new versions of racer.

racer-rust-src-path defaults to rustup source directory

---

racer.el

Currently M-. does not work in an indirect cloned buffer created with C-x 4 c, as the indirect buffer does not have a file name directly. This patch gets the file name of the base buffer if the current buffer is an indirect buffer, otherwise it gets the file name of the current buffer.

Fix getting file name of indirect buffers

---

Cask

Fixes racer.el obtained via El-Get if "f" isn't already installed.

Cask: add dependency declaration for "f"

---

racer.el

I've written a small function to show the docstring without opening a new window:

Add function to show docstrings in a tooltip

---

README.md

Updated the readme to make it explicit that you will need to use a nightly release of rust in order to install racer.
This one got me, figured I'd help out the next person 👍

Make Nightly Requirement Explicit

---

racer.el

I tried my hand at issue #37. After completion, if the matchtype was a function, it tries to extract and insert the function arguments in the same way that was referenced in the issue. If there is a `self` argument in the beginning of the argument list, that one is not inserted.
I don't know much Emacs Lisp, so please let me know if there is a mistake or something I can improve.

Insert argument placeholders for function completions

---

README.md
racer.el

This commit replaces blocking `call-process` with asynchronous `make-process`.
Instead we block explicitly until racer process output is received or timeout
fires. To that effect we introduce two new custom variables
`racer-command-timeout` and `racer-eldoc-timeout`. The latter is important because
Eldoc runs every time Emacs is idle but the user should be able to start typing
any time without waiting on the racer process. Timeout value of nil will wait for
the output indefinitely.
I observed that the first time `racer` shell process runs it may take a while to
respond probably due to indexing. Following responses tend to be snappy. For that
reason and because user asking for completion is likely ok with a bit of waiting
`racer-command-timeout` defaults to nil. `racer-eldoc-timeout` …

Switch to asynchronous racer command with timeouts.

---

racer.el
test/racer-test.el

- In cases where there are multiple matching results, display all matching the
prefix specified via completing-read.
- Sort multiple results by length of docstring which is a good heuristic for
getting the information you want at the top of the help buffer.

Add support for multiple results via racer-describe

---

racer.el

According to HEAD NEWS, "The 'when' argument of `make-obsolete` and related functions is mandatory".

fix define-obsolete-function-alias error in Emacs28

---

racer.el

Used for compatibility with the latest rust version.

Change the default value of racer-rust-src-path
